<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Audit Log Report') }}</title>
    <style>
        body { font-family: sans-serif; font-size: 10pt; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; vertical-align: top; }
        th { background-color: #f2f2f2; }
        .header { margin-bottom: 20px; }
        .meta { font-size: 0.9em; color: #555; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ __('Audit Log Report') }}</h1>
        <div class="meta">
            <p><strong>{{ __('Date Range') }}:</strong> {{ $fromDate }} - {{ $toDate }}</p>
            <p><strong>{{ __('Generated By') }}:</strong> {{ auth()->user()->name }}</p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 10%;">{{ __('Date') }}</th>
                <th style="width: 12%;">{{ __('Modified By') }}</th>
                <th style="width: 8%;">{{ __('Event ID') }}</th>
                <th style="width: 12%;">{{ __('Affected User') }}</th>
                <th style="width: 10%;">{{ __('Team') }}</th>
                <th style="width: 10%;">{{ __('Work Center') }}</th>
                <th style="width: 38%;">{{ __('Differences') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($history as $record)
                @php
                    $user = \App\Models\User::find($record->user_id);
                    $userName = $user ? $user->name . ' ' . $user->family_name1 : __('Unknown') . ' (' . $record->user_id . ')';
                    
                    // Extract event information from JSON
                    $eventData = json_decode($record->modified_event ?? $record->original_event, true);
                    $eventId = $eventData['id'] ?? '-';
                    $affectedUserId = $eventData['user_id'] ?? null;
                    $affectedUser = $affectedUserId ? \App\Models\User::find($affectedUserId) : null;
                    $affectedUserName = $affectedUser ? $affectedUser->name . ' ' . $affectedUser->family_name1 : '-';
                    
                    $teamId = $eventData['team_id'] ?? null;
                    $team = $teamId ? \App\Models\Team::find($teamId) : null;
                    $teamName = $team ? $team->name : '-';
                    
                    $workCenterId = $eventData['work_center_id'] ?? null;
                    $workCenter = $workCenterId ? \App\Models\WorkCenter::find($workCenterId) : null;
                    $workCenterName = $workCenter ? $workCenter->name : '-';
                @endphp
                <tr>
                    <td style="font-size: 0.85em;">{{ \Carbon\Carbon::parse($record->created_at)->format('d/m/Y H:i') }}</td>
                    <td style="font-size: 0.85em;">{{ $userName }}</td>
                    <td style="font-size: 0.85em; text-align: center;">#{{ $eventId }}</td>
                    <td style="font-size: 0.85em;">{{ $affectedUserName }}</td>
                    <td style="font-size: 0.85em;">{{ $teamName }}</td>
                    <td style="font-size: 0.85em;">{{ $workCenterName }}</td>
                    <td>
                        @if(count($record->differences ?? []) > 0)
                            <table style="width: 100%; border: none; margin-top: 0;">
                                <thead>
                                    <tr>
                                        <th style="width: 30%; background-color: #f9fafb; font-size: 0.8em;">{{ __('Field') }}</th>
                                        <th style="width: 35%; background-color: #f9fafb; font-size: 0.8em;">{{ __('Old') }}</th>
                                        <th style="width: 35%; background-color: #f9fafb; font-size: 0.8em;">{{ __('New') }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($record->differences as $key => $diff)
                                        <tr>
                                            <td style="font-weight: bold; font-size: 0.75em;">{{ $key }}</td>
                                            <td style="font-size: 0.75em; word-break: break-all;">
                                                @if($diff['type'] == 'added')
                                                    <span style="font-style: italic; color: #9ca3af;">{{ __('(New)') }}</span>
                                                @else
                                                    {{ $diff['original'] }}
                                                @endif
                                            </td>
                                            <td style="font-size: 0.75em; word-break: break-all;">
                                                @if($diff['type'] == 'deleted')
                                                    <span style="font-style: italic; color: #9ca3af;">{{ __('(Deleted)') }}</span>
                                                @else
                                                    {{ $diff['modified'] }}
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @else
                             <div style="font-style: italic; color: #6b7280; font-size: 0.8em;">{{ __('No differences') }}</div>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>
