<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Audit Log Report') }}</title>
    <style>
        * { font-size: 9pt !important; } /* Force base font size */
        body { font-family: DejaVu Sans, sans-serif; font-size: 9pt; margin: 0; padding: 0; }
        .header { margin-bottom: 8px; border-bottom: 1px solid #333; padding-bottom: 4px; }
        .meta { font-size: 8pt; color: #555; margin: 0; padding: 0; }
        .meta p { margin: 2px 0; }
        
        .record { 
            margin-bottom: 10px; 
            padding: 6px; 
            border: 0.5px solid #ccc; 
            page-break-inside: avoid;
            background-color: #fafafa;
        }
        
        .record-header {
            display: table;
            width: 100%;
            margin-bottom: 6px;
            padding-bottom: 4px;
            border-bottom: 1px solid #ddd;
        }
        
        .record-info {
            display: table-cell;
            width: 50%;
            font-size: 8pt;
        }
        
        .record-info-label {
            color: #999;
            font-size: 7pt;
            text-transform: uppercase;
            display: block;
        }
        
        .record-info-value {
            color: #000;
            font-weight: bold;
            font-size: 8pt;
        }
        
        .changes-title {
            font-size: 9pt;
            font-weight: bold;
            margin-bottom: 4px;
            color: #333;
        }
        
        .diff-table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }
        
        .diff-table th {
            background-color: #f5f5f5;
            text-align: left;
            padding: 4px;
            font-size: 7pt;
            color: #666;
            text-transform: uppercase;
            border-bottom: 1px solid #ddd;
            font-weight: bold;
            height: auto;
            min-height: 15px;
        }
        
        .diff-table td {
            padding: 5px;
            font-size: 8.5pt !important;
            border-bottom: 0.5px solid #eee;
            vertical-align: top;
            word-wrap: break-word;
            overflow-wrap: break-word;
            word-break: break-all;
            height: auto !important;
            min-height: 20px !important;
        }
        
        .col-field { width: 20%; font-weight: bold; color: #000; }
        .col-old { width: 40%; word-break: break-all; }
        .col-new { width: 40%; word-break: break-all; }
        
        .value-old {
            color: #c53030;
            background-color: #fee;
            padding: 2px 4px;
            display: inline-block;
            font-size: 8.5pt !important;
        }
        
        .value-new {
            color: #276749;
            background-color: #efe;
            padding: 2px 4px;
            display: inline-block;
            font-size: 8.5pt !important;
        }
        
        .value-empty {
            font-style: italic;
            color: #999;
            background-color: #f5f5f5;
            padding: 2px 4px;
            display: inline-block;
            font-size: 8.5pt !important;
        }
        
        .no-diff {
            font-style: italic;
            color: #999;
            font-size: 8pt;
            padding: 4px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 style="font-size: 14pt; margin: 0 0 4px 0;">{{ __('Audit Log Report') }}</h1>
        <div class="meta">
            <p><strong>{{ __('Date Range') }}:</strong> {{ $fromDate }} - {{ $toDate }} | <strong>{{ __('Generated By') }}:</strong> {{ auth()->user()->name }}</p>
        </div>
    </div>

    @foreach($history as $record)
        @php
            $user = \App\Models\User::find($record->user_id);
            $userName = $user ? $user->name . ' ' . $user->family_name1 : __('Unknown');
            $date = \Carbon\Carbon::parse($record->created_at)->format('d/m/Y H:i:s');
            
            // Extract event information from JSON
            $eventData = json_decode($record->modified_event ?? $record->original_event, true);
            $eventId = $eventData['id'] ?? '-';
            $affectedUserId = $eventData['user_id'] ?? null;
            $affectedUser = $affectedUserId ? \App\Models\User::find($affectedUserId) : null;
            $affectedUserName = $affectedUser ? $affectedUser->name . ' ' . $affectedUser->family_name1 : '-';
            
            $teamId = $eventData['team_id'] ?? null;
            $team = $teamId ? \App\Models\Team::find($teamId) : null;
            $teamName = $team ? $team->name : '-';
            
            $workCenterId = $eventData['work_center_id'] ?? null;
            $workCenter = $workCenterId ? \App\Models\WorkCenter::find($workCenterId) : null;
            $workCenterName = $workCenter ? $workCenter->name : '-';
        @endphp
        
        <div class="record">
            <div class="record-header">
                <div class="record-info">
                    <span class="record-info-label">{{ __('Modified By') }}</span>
                    <span class="record-info-value">{{ $userName }}</span>
                </div>
                <div class="record-info" style="text-align: right;">
                    <span class="record-info-label">{{ __('Date') }}</span>
                    <span class="record-info-value">{{ $date }}</span>
                </div>
            </div>
            
            <div class="record-header">
                <div class="record-info">
                    <span class="record-info-label">{{ __('Event ID') }}</span>
                    <span class="record-info-value">#{{ $eventId }}</span>
                </div>
                <div class="record-info">
                    <span class="record-info-label">{{ __('Affected User') }}</span>
                    <span class="record-info-value">{{ $affectedUserName }}</span>
                </div>
            </div>
            
            <div class="record-header">
                <div class="record-info">
                    <span class="record-info-label">{{ __('Team') }}</span>
                    <span class="record-info-value">{{ $teamName }}</span>
                </div>
                <div class="record-info">
                    <span class="record-info-label">{{ __('Work Center') }}</span>
                    <span class="record-info-value">{{ $workCenterName }}</span>
                </div>
            </div>
            
            @if(count($record->differences ?? []) > 0)
                <div class="changes-title">{{ __('Detected Changes') }}</div>
                
                <table class="diff-table">
                    <thead>
                        <tr>
                            <th class="col-field">{{ __('Field') }}</th>
                            <th class="col-old">{{ __('Old Value') }}</th>
                            <th class="col-new">{{ __('New Value') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($record->differences as $key => $diff)
                            @php
                                $oldValue = $diff['original'] ?? null;
                                $newValue = $diff['modified'] ?? null;
                                $oldIsEmpty = $diff['type'] == 'added' || is_null($oldValue) || $oldValue === '' || $oldValue === 'null';
                                $newIsEmpty = $diff['type'] == 'deleted' || is_null($newValue) || $newValue === '' || $newValue === 'null';
                                
                                // Format JSON to allow line wrapping by adding spaces after punctuation
                                if (!$oldIsEmpty && (str_contains($oldValue, '{') || str_contains($oldValue, '['))) {
                                    $oldValue = preg_replace('/([,:\{\}\[\]])(?!\s)/', '$1 ', $oldValue);
                                }
                                if (!$newIsEmpty && (str_contains($newValue, '{') || str_contains($newValue, '['))) {
                                    $newValue = preg_replace('/([,:\{\}\[\]])(?!\s)/', '$1 ', $newValue);
                                }
                            @endphp
                            <tr>
                                <td class="col-field">{{ $key }}</td>
                                <td class="col-old">
                                    @if($oldIsEmpty)
                                        <span class="value-empty">{{ __('Empty') }}</span>
                                    @else
                                        <span class="value-old">{{ $oldValue }}</span>
                                    @endif
                                </td>
                                <td class="col-new">
                                    @if($newIsEmpty)
                                        <span class="value-empty">{{ __('Empty') }}</span>
                                    @else
                                        <span class="value-new">{{ $newValue }}</span>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <div class="no-diff">{{ __('No differences') }}</div>
            @endif
        </div>
    @endforeach
</body>
</html>
