<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Audit Log Report') }}</title>
    <style>
        body { font-family: sans-serif; font-size: 10pt; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; vertical-align: top; }
        th { background-color: #f2f2f2; }
        .header { margin-bottom: 20px; }
        .meta { font-size: 0.9em; color: #555; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ __('Audit Log Report') }}</h1>
        <div class="meta">
            <p><strong>{{ __('Date Range') }}:</strong> {{ $fromDate }} - {{ $toDate }}</p>
            <p><strong>{{ __('Generated By') }}:</strong> {{ auth()->user()->name }}</p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>{{ __('Date') }}</th>
                <th>{{ __('User') }}</th>
                <th>{{ __('Table') }}</th>
                <th>{{ __('Original Data') }}</th>
                <th>{{ __('Modified Data') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($history as $record)
                @php
                    $user = \App\Models\User::find($record->user_id);
                    $userName = $user ? $user->name . ' ' . $user->family_name1 : __('Unknown') . ' (' . $record->user_id . ')';
                @endphp
                <tr>
                    <td>{{ \Carbon\Carbon::parse($record->created_at)->format('d/m/Y H:i:s') }}</td>
                    <td>{{ $userName }}</td>
                    <td>{{ $record->tablename }}</td>
                    <td><pre style="white-space: pre-wrap; font-size: 0.8em;">{{ $record->original_event }}</pre></td>
                    <td><pre style="white-space: pre-wrap; font-size: 0.8em;">{{ $record->modified_event }}</pre></td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>
